# Generated by Django 3.2.7 on 2021-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'db_table': 'Divisao',
                'ordering': ['codigo'],
            },
        ),
    ]
