# Generated by Django 3.2.7 on 2021-09-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolucao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.divisao', verbose_name='Divisão')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.grupo', verbose_name='Grupo')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.subgrupo', verbose_name='SubGrupo')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.tipologia', verbose_name='Tipologia')),
            ],
            options={
                'verbose_name': 'Licenca',
                'verbose_name_plural': 'Licencas',
                'db_table': 'licenca',
                'ordering': ['subgrupo'],
            },
        ),
    ]
