# Generated by Django 3.2.7 on 2021-09-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'db_table': 'Divisao',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('descricao', models.CharField(max_length=110)),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.divisao', verbose_name='Divisão')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
                'ordering': ['divisao'],
            },
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'SubGrupo',
                'verbose_name_plural': 'SubGrupos',
                'db_table': 'subgrupo',
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='Unidade_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('und_medida_desc', models.CharField(max_length=255, verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidade_medida',
                'ordering': ['und_medida_desc'],
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('p_poluidor', models.CharField(max_length=1, verbose_name='Potencial Poluidor')),
                ('descricao', models.CharField(max_length=100)),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.subgrupo', verbose_name='SubGrupo')),
                ('und_medida_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolucao.unidade_medida', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologias',
                'db_table': 'tipologia',
                'ordering': ['subgrupo'],
            },
        ),
    ]
